# Setup
title: 碳基生物
description: Make Every Day Count.
url: https://shuangjiang169.github.io/myrica.github.io/
avatar: /avatar.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: myrica
  card: summary
logo: logo.png
social:
  name: myrica
  links:
    - https://github.com/shuangjiang169
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: myrica
  url: https://github.com/shuangjiang169
  email: anny169@foxmail.com
